* What the tortoise said to Achilles
** Overview
To use a reasoning principle, we demand a justification of that reasoning principle.
But to use said justifcation to draw conclusion, we demand even more justification for the use of that justification ad infinitum.

*** Eg
MP: Suppose A and A implies B, conclude B.
To use MP, we need to justify it.
Ok, so we provide a justification C.
But to use the justification C to justify the use of MP, we need to justify the use of C.
This repeats ad infinitum.

** Moral of the story
At some point, we need to take something as self-evident (primitive, requiring no justification).

** Question 1
Is taking something as self-evident problematic?

*** Relativized PoV
Even if I build my arguments based on a collection of things that I consider self-evident, I can come back and demand justifications for those self-evident things.
That is, we have stratified reasoning.

** Question 2
Can something be "objectively" self-evident?

*** Our perspective
We believe that identity is self-evident.
"Given A, derive A."


** Question 3
What should be considered self-evident?

*** Our perspective
The answer depends on what we want to describe with the language.

Is LEM self-evident?
"either p or not p is true."
"there is either a piece of evidence of p or a refutation of p"

Is DNE self-evident?
"The complement of the complement of A."
"I don't dislike chocolate."

*** Programming language example
In the design of programming languages, we often need to choose a sensible set of primitives.
Of course, we implement high-level primitives with lower level-primitives.
This brings us back to the first question.

* The justification of deduction

** Question 4
Looking at the justifications for MMP and MM, why are we more inclined to accept the one for MMP than the one for MM?
What does Haack mean? Choosing between MMP or MM, or both?

*** Opinion
1. When we say A -> B is true, the metal image we have is when I can observe A then I can also observe B.
Eg. If the sun shines, I go for a walk. This gives me two pieces of information: When I observe that the sun is shining, then I go for a walk.
2. Now consider MM. If we observe that I'm going for a walk, then MM says the sun is shining. What if we take the contrapositive?
If I don't go for a walk, then the sun is not shining. Consider the scenario where the sun is not shining, MM says I don't go for a walk.

Haack argues that if the meaning of -> is partially given by it inference rules, then MM can be justified.
We think Haack is making the implicit assumption that -> is the "if ... then ..." construct, but we should not make this assumption at this point because -> could very well mean "... if ..." In this case, MM is not problematic at all.
In fact, if we choose both then -> just means <-> in the ususal sense.
We use A -> B because we often phrase sentences in this structure, and this syntax reflect this tendency.
Do we need justification for this? Both seem reasonable, we just happen to choose MMP.
In contrast, if we define (at least classically) A -> B := (A and B) or (not A and not B), then we can introduce simplication /-> := not A or B, which corresponds to the usual implication.
In this case, we have successfully done nothing. More specifically, we have not got any steps closer to justifying implication/simplication.

** Question 5
Do you think logic is revisable?

*** Opinion
Yes.

*** PL opinion
Yes. Programming languages evolve.
